// Need to use the React-specific entry point to import `createApi`
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react"

type Task = {
  id: number
  todo: string
  completed: string
}

type TasksApiResponse = {
  tasks: Task[]
  total: number
  skip: number
  limit: number
}

// Define a service using a base URL and expected endpoints
export const tasksApiSlice = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: "https://dummyjson.com/todos" }),
  reducerPath: "tasksApi",
  // Tag types are used for caching and invalidation.
  tagTypes: ["Tasks"],
  endpoints: build => ({
    // Supply generics for the return type (in this case `TasksApiResponse`)
    // and the expected query argument. If there is no argument, use `void`
    // for the argument type instead.
    getTasks: build.query<TasksApiResponse, number>({
      query: (limit = 10) => `?limit=${limit.toString()}`,
      // `providesTags` determines which 'tag' is attached to the
      // cached data returned by the query.
      providesTags: (_result, _error, id) => [{ type: "Tasks", id }],
    }),
  }),
})

// Hooks are auto-generated by RTK-Query
export const { useGetTasksQuery } = tasksApiSlice